blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/ericcayers-ai/panopto-course-assistant/blob/master/CODE_OF_CONDUCT.md
    about: How we expect everyone to participate in this project.
